import jsPDF from "jspdf"
import "jspdf-autotable"

export interface InvoiceItem {
  description: string
  quantity: number
  unitPrice: number
  total: number
}

export interface InvoiceData {
  invoiceNumber: string
  clientName: string
  clientEmail?: string
  items: InvoiceItem[]
  subtotal: number
  tax: number
  total: number
  currency: string
  dueDate?: string
  notes?: string
  createdAt: string
  companyName?: string
}

export function generateInvoicePDF(invoice: InvoiceData): jsPDF {
  const doc = new jsPDF()
  const currency = invoice.currency || "USD"
  const currencySymbol = getCurrencySymbol(currency)

  // Header
  doc.setFontSize(24)
  doc.setTextColor(59, 130, 246) // Blue
  doc.text("INVOICE", 20, 30)

  doc.setFontSize(10)
  doc.setTextColor(107, 114, 128) // Gray
  doc.text(invoice.companyName || "Your Company", 20, 40)

  // Invoice details (right side)
  doc.setFontSize(10)
  doc.setTextColor(55, 65, 81)
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 140, 25)
  doc.text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 140, 32)
  if (invoice.dueDate) {
    doc.text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, 140, 39)
  }

  // Bill To
  doc.setFontSize(11)
  doc.setTextColor(59, 130, 246)
  doc.text("Bill To:", 20, 58)
  doc.setTextColor(55, 65, 81)
  doc.setFontSize(10)
  doc.text(invoice.clientName, 20, 65)
  if (invoice.clientEmail) {
    doc.text(invoice.clientEmail, 20, 72)
  }

  // Divider
  doc.setDrawColor(229, 231, 235)
  doc.setLineWidth(0.5)
  doc.line(20, 80, 190, 80)

  // Items table
  const tableData = invoice.items.map((item) => [
    item.description,
    item.quantity.toString(),
    `${currencySymbol}${item.unitPrice.toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
    `${currencySymbol}${item.total.toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
  ])

  ;(doc as any).autoTable({
    startY: 85,
    head: [["Description", "Qty", "Unit Price", "Total"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: 255,
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [55, 65, 81],
    },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { cellWidth: 25, halign: "center" },
      2: { cellWidth: 35, halign: "right" },
      3: { cellWidth: 35, halign: "right" },
    },
    margin: { left: 20, right: 20 },
  })

  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 10
  doc.setFontSize(10)
  doc.text("Subtotal:", 130, finalY)
  doc.text(
    `${currencySymbol}${invoice.subtotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
    175,
    finalY,
    { align: "right" }
  )

  doc.text(`Tax:`, 130, finalY + 7)
  doc.text(
    `${currencySymbol}${invoice.tax.toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
    175,
    finalY + 7,
    { align: "right" }
  )

  doc.setDrawColor(59, 130, 246)
  doc.setLineWidth(0.8)
  doc.line(130, finalY + 11, 190, finalY + 11)

  doc.setFontSize(12)
  doc.setTextColor(59, 130, 246)
  doc.text("Total:", 130, finalY + 19)
  doc.text(
    `${currencySymbol}${invoice.total.toLocaleString(undefined, { minimumFractionDigits: 2 })}`,
    175,
    finalY + 19,
    { align: "right" }
  )

  // Notes
  if (invoice.notes) {
    doc.setFontSize(9)
    doc.setTextColor(107, 114, 128)
    doc.text("Notes:", 20, finalY + 35)
    doc.text(invoice.notes, 20, finalY + 42)
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(156, 163, 175)
  doc.text("Generated by Business Analytics Dashboard", 105, 285, { align: "center" })

  return doc
}

export function getCurrencySymbol(currency: string): string {
  const symbols: Record<string, string> = {
    USD: "$",
    EUR: "€",
    GBP: "£",
    JPY: "¥",
    CAD: "C$",
    AUD: "A$",
    INR: "₹",
    CNY: "¥",
    BRL: "R$",
    MXN: "MX$",
    KRW: "₩",
    CHF: "CHF ",
    SEK: "kr ",
    NOK: "kr ",
    DKK: "kr ",
    NZD: "NZ$",
    SGD: "S$",
    HKD: "HK$",
    ZAR: "R ",
  }
  return symbols[currency] || "$"
}
