name: Call Todo Reminder API

on:
  schedule:
    - cron: '*/2 * * * *' # every 2 minutes

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call reminder endpoint
        run: |
          curl -X GET "https://business-analytics-zeta.vercel.app/api/todo-reminder" -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
